### ISSUE TITLE
Make it play along with opacity utilities...

### ISSUE THREAD

**Issue by crswll** [crswll/tailwindcss-theme-swapper#8]
With tailwind you can do something like:

```css
{
  primary: '#f00',
}
```

Which gives you something like:

```css
.text-primary {
  --tw-text-opacity: 1;
  color: rgb(255 0 0 / var(--tw-text-opacity, 1))
}
```

With custom properties this is more difficult to do. We'd need to essentially translate the hex colors to `r g b` and do something like this but I don't know if this is too much magic or not (especially if things aren't defined as hex).

```css
:root {
  --colors-primary: 255 0 0;
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgb(var(--colors-primary) / var(--tw-text-opacity, 1));
}
```

This will be useful. Will definitely need some logic around if we should do this for a given value or not.

```js
const colorNameWithVariable = name => ({ opacityVariable, opacityValue }) => {
  if (opacityValue !== undefined) {
    return `rgb(var(--${name}) / ${opacityValue})`
  }
  if (opacityVariable !== undefined) {
    return `rgb(var(--${name}) / var(${opacityVariable}, 1))`
  }
  return `rgb(var(--${name}))`
}
```
